apiVersion: v1
kind: Service
metadata:
  name: shell-service
  namespace: tools
  labels:
    app: shell
spec:
  ports:
  - name: http
    port: 4200
    protocol: TCP
    targetPort: 4200
  selector:
    app: shell
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shell-deploy
  namespace: tools
spec:
  selector:
    matchLabels:
      app: shell
  replicas: 1
  template:
    metadata:
      labels:
        app: shell
    spec:
      containers:
      - name: shell
        image: sybex/shellinabox:1.2.${DRONE_BUILD_NUMBER}
        env:
        - name: SIAB_SSL
          value: "false"
        - name: SIAB_HOME
          valueFrom:
            secretKeyRef:
              name: shell-cred
              key: homedir
        - name: SIAB_USER
          valueFrom:
            secretKeyRef:
              name: shell-cred
              key: username
        - name: SIAB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: shell-cred
              key: password
        resources:
          limits:
            cpu: 1000m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 10Mi
        ports:
        - containerPort: 4200
          protocol: TCP
        volumeMounts:
        - mountPath: /home
          name: shell-data
        livenessProbe:
          httpGet:
            path: /
            port: 4200
          initialDelaySeconds: 300
          timeoutSeconds: 30
      - image: docker:18.06.3-dind
        imagePullPolicy: Always
        name: dind
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities: {}
          privileged: true
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dockerhub
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: shell-data
        persistentVolumeClaim:
          claimName: shell-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shell-pvc
  namespace: tools
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
