apiVersion: v1
kind: Service
metadata:
  name: shell-service
  namespace: tools
  labels:
    name: shell
spec:
  ports:
  - port: 4200
    protocol: TCP
    targetPort: 4200
  selector:
    name: shell
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shell-deploy
  namespace: tools
spec:
  selector:
    matchLabels:
      app: shell
  replicas: 1
  template:
    metadata:
      labels:
        app: shell
    spec:
      containers:
      - name: shell
        image: sybex/shellinabox:latest
        resources:
          limits:
            cpu: 1000m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 10Mi
        ports:
        - containerPort: 4200
          protocol: TCP
        volumeMounts:
        - mountPath: /home
          name: shell-volume
        livenessProbe:
          httpGet:
            path: /
            port: 4200
          initialDelaySeconds: 300
          timeoutSeconds: 30
      volumes:
      - name: shell-volume
        emptyDir: {}
